version: '3'
services:
  postgresql:
    image: postgres:12.6
    volumes:
    - ./postgresql_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    volumes:
    - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 5050:80